###########
# Project #
###########

project:
  type: "book"
  output-dir: "book_scrnaseq"

book:
  title: |
    | scrnaseq2
    | Single-cell analysis results
  subtitle: "bfx2696"
  chapters:
  - "index.qmd"
  - "modules/1_read_data/read_data.qmd"
  - "modules/2_qc_filtering/rna/qc_filtering.qmd"
  - "modules/2_qc_filtering/adt/qc_filtering.qmd"
  - "modules/3_normalization/rna/normalization.qmd"
  - "modules/3_normalization/adt/normalization.qmd"
  - "modules/4_dimensionality_reduction/rna/dimensionality_reduction.qmd"
  - "modules/4_dimensionality_reduction/adt/dimensionality_reduction.qmd"
  - "modules/5_clustering_umap/clustering_umap.qmd"
  - "modules/6_clusterqc/clusterqc.qmd"
  - "modules/7_cluster_annotation/cluster_annotation.qmd"
  - "modules/8_cluster_composition/cluster_composition.qmd"
#  - "modules/10_deg_analysis/deg_analysis.qmd"
  - "modules/9_export/export.qmd"
  - "references.qmd"

####################
# Execute defaults #
####################

execute: 
  freeze: "auto"
  echo: true
  message: false
  warning: false

##########
# Params #
##########
# Detailed descriptions of all parameters can be found in the respective modules
params:
  general:

    # General
    project_id: "project"
    species: "mus_musculus"
    ensembl: 104

    # Technical
    verbose: true
    on_disk_counts: true
    on_disk_use_tmp: true
    cores: 8

    # Analysis
    barcode_qc:
    - "nCount_RNA"
    - "nFeature_RNA"
    - "pMito_RNA"
    - "pRibosomal_RNA"
    - "pGlobin_RNA"
    - "pERCC_RNA"
    - "pXIST_RNA"
    - "pChrY_RNA"
    - "doublet_scores"
    use_sketching: false

  modules:
  
    read_data:
      default_assay: "RNA"
      datasets_file: "datasets/bfx2696.xlsx"
      downsample_barcodes_n: null
      downsample_barcodes_equally: false
      downsample_features_n: null
      parse_plate_information: true
      plate_information_regex: "_(\\d+)_([A-Z])(\\d+)$"
      plate_information_update_identity: true
      spatial_coordinate_type:
        - "centroids"
        - "segmentations"
      visiumhd_bin_sizes:
      - 8
      - 16

    qc_filtering_rna:
      default_assay: "RNA"
      barcode_qc_cor:
      - "nFeature_RNA nCount_RNA"
      - "nFeature_RNA pMito_RNA"
      barcode_filter: !expr list(
          nFeature_RNA=c(200, NA), 
          pMito_RNA=c(0, 50))
      feature_filter: !expr list(
        min_counts = 1,
        min_cells = 3)
      samples_to_drop: null
      samples_min_cells: 10
      
    qc_filtering_adt:
      default_assay: "ADT"
      barcode_qc_cor:
      - "nFeature_ADT nCount_ADT"
      barcode_filter: !expr list(
          nFeature_ADT=c(5, NA))
      feature_filter: !expr list(
        min_counts = 1,
        min_cells = 3)
      samples_to_drop: null
      samples_min_cells: 10
      barcode_qc:
      - "nCount_ADT"
      - "nFeature_ADT"

    normalization_rna:
      default_assay: "RNA"
      normalization_method: "lognorm"
      cellcycle_remove: false
      cellcycle_remove_all: false
      vars_to_regress: null
      feature_selection_method: "vst"
      num_variable_features: 3000
      num_barcodes_for_sketching: 50000
    
    normalization_adt:
      default_assay: "ADT"
      normalization_method: "log"
      cellcycle_remove: false
      cellcycle_remove_all: false
      vars_to_regress: null
      feature_selection_method: "vst"
      num_variable_features: 3000
      num_barcodes_for_sketching: 50000

    dimensionality_reduction_rna:
      default_assay: "RNA"
      dimensionality_reduction_method: "pca"
      dim_n_compute: 50
      dim_n: 20
      integration_methods: null
      CCAIntegration: null
      RPCAIntegration: null
      HarmonyIntegration: null
      FastMNNIntegration: null
      scVIIntegration: null

    dimensionality_reduction_adt:
      default_assay: "ADT"
      dimensionality_reduction_method: "pca"
      dim_n_compute: 15
      dim_n: 12
      integration_methods: null
      CCAIntegration: null
      RPCAIntegration: null
      HarmonyIntegration: null
      FastMNNIntegration: null
      scVIIntegration: null

    clustering_umap:
      default_assay: "RNA"
      dim_n: 20
      cluster_resolution:
      - 0.5
      - 0.25
      - 0.75
      - 1
      cluster_k: 20
      umap_k: 30

    cluster_annotation:
      default_assay: "RNA"
      marker_pct: 0.25
      marker_log2FC: 0.25
      latent_vars: null
      file_known_markers: null

    export:
      export_metadata: true
      create_loupe_file: true
      export_xenium_analysis_file: false
      export_cellxgene: true
      export_sc: true
      convert_on_disk_layers: false
