###########
# Profile #
###########

profile: 
  default: scrnaseq

###########
# Project #
###########

project:
  type: "default"
  output-dir: "book_default"
  execute-dir: "project"
  post-render: 
    - "R/collect_module_results.R"
    
book:
  sidebar:
    logo: "docs/scrnaseq2_cover.png"

bibliography: "misc/references.bib"
csl: "misc/nature.csl"

#################
# Knitr options #
#################
knitr:
  opts_chunk:
    dpi: 300
    fig-width: 8
    fig-height: 5
    results: "hold"
    timeit: null
    tidy: "styler"
    tidy-opts:
      strict: false

##################
# Format options #
##################

format:
  html:
    number-sections: false
    grid:
      sidebar-width: "300px"
      margin-width: "0px"
      body-width: "1000px"
    theme:
    - "sandstone"
    embed-resources: false
    code-fold: true
    code-summary: "Code"
    code-link: true
    code-block-bg: true
    css: "css/style.css"
    df-print: "kable"
    toc: true
    toc-depth: 2
    toc-location: left
    fig-format: "png"
    keep-md: true
    #execute:
    #  echo: false
    #  message: false
    #  warning: false
    knitr:
      opts_chunk:
        dev:
        - "png"
        - "cairo_pdf"
        dev.args:
          png:
            type: "cairo"
  # pdf:
  #   documentclass: "scrreprt"
  #   code-block-bg: true
  #   df-print: "kable"
  #   toc: true
  #   toc-depth: 2
  #   lof: true
  #   lot: true
  #   fig-format: "pdf"
  #   keep-tex: false
  #   #execute:
  #   #  echo: false
  #   #  message: false
  #   #  warning: false
  #   knitr:
  #     opts_chunk:
  #       dev:
  #       - "cairo_pdf"
  #       - "png"
  #       dev.args:
  #         png:
  #           type: "cairo"
  #   include-in-header:
  #     text: |
  #       \usepackage{fvextra}
  #       \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,breakanywhere,commandchars=\\\{\}}
  # docx:
  #   reference-doc: "misc/template.docx"
  #   page-width: 8.3
  #   code-block-bg: true
  #   df-print: "kable"
  #   toc: true
  #   toc-depth: 2
  #   fig-format: "png"
  #   #execute:
  #   #  echo: false
  #   #  message: false
  #   #  warning: false
  #   knitr:
  #     opts_chunk:
  #       dev:
  #       - "png"
  #       - "cairo_pdf"
  #       dev_args:
  #         png:
  #           type: "cairo"

#########
# Other #
#########

# Date
date: "now"
date-modified: "last-modified"
date-format: "DD-MM-YYYY HH:mm:ss"
