###########
# Project #
###########

project:
  type: "book"
  output-dir: "book_scrnaseq"

book:
  title: |
    | scrnaseq2
    | Single-cell analysis results
  subtitle: "bfx1234"
  chapters:
  - "index.qmd"
  - "modules/1_read_data/read_data.qmd"
  - "modules/2_qc_filtering/rna/qc_filtering.qmd"
  - "modules/3_normalization/rna/normalization.qmd"
  - "modules/4_dimensionality_reduction/rna/dimensionality_reduction.qmd"
  - "modules/5_clustering_umap/clustering_umap.qmd"
  - "modules/6_clusterqc/clusterqc.qmd"
  - "modules/7_cluster_annotation/cluster_annotation.qmd"
  - "modules/8_cluster_composition/cluster_composition.qmd"
  - "modules/9_export/export.qmd"
  - "references.qmd"

####################
# Execute defaults #
####################

execute: 
  freeze: "auto"
  echo: true
  message: false
  warning: false

##########
# Params #
##########
# Detailed descriptions of all parameters can be found in the respective modules
params:
  general:

    # General
    project_id: "bfx2383"
    species: "danio_rerio"
    ensembl: 104

    # Technical
    verbose: true
    on_disk_counts: false
    on_disk_use_tmp: false
    cores: 8

    # Analysis
    barcode_qc:
    - "nCount_RNA"
    - "nFeature_RNA"
    - "pMito_RNA"
    - "pRibosomal_RNA"
    - "pGlobin_RNA"
    - "pERCC_RNA"
    - "pXIST_RNA"
    - "pChrY_RNA"
    - "scrublet_doublet_scores"
    use_sketching: false

  modules:
  
    read_data:
      default_assay: RNA
      datasets_file: "datasets/bfx2383.xlsx"
      downsample_barcodes_n: null
      downsample_barcodes_equally: false
      downsample_features_n: null
      parse_plate_information: true
      plate_information_regex: "_(\\d+)_([A-Z])(\\d+)$"
      plate_information_update_identity: true
      spatial_coordinate_type:
        - "centroids"
        - "segmentations"

    qc_filtering_rna:
      barcode_qc_cor:
      - "nFeature_RNA nCount_RNA"
      - "nFeature_RNA pMito_RNA"
      barcode_filter: !expr list(
        nCount_RNA = c(25000, NA),
        nFeature_RNA = c(500, NA),
        pMito_RNA = c(NA, 30))
      feature_filter: !expr list(
        min_counts = 1,
        min_cells = 3)
      samples_to_drop: c("B30GFP", "PC", "NC")
      samples_min_cells: 10

    normalization_rna:
      normalization_method: "lognorm"
      cellcycle_remove: false
      cellcycle_remove_all: false
      vars_to_regress: null
      feature_selection_method: "vst"
      num_variable_features: 3000
      num_barcodes_for_sketching: 50000

    dimensionality_reduction_rna:
      dimensionality_reduction_method: "PCA"
      dim_n_compute: 70
      dim_n: 50
      integration_methods: null
      CCAIntegration: null
      RPCAIntegration: null
      HarmonyIntegration: null
      FastMNNIntegration: null
      scVIIntegration: null

    clustering_umap:
      dim_n: 30
      cluster_resolution:
      - 1
      - 0.25
      - 0.5
      - 0.75
      - 1.25
      - 1.5
      cluster_k: 15
      umap_k: 15

    cluster_annotation:
      marker_pct: 0.25
      marker_log2FC: 0.25
      latent_vars: null
      file_known_markers: "datasets/bfx2383_knownMarkers.xlsx"

    export:
      export_loupe: true
      export_loupe_normalized: true
      export_cellxgene: true
      export_sc: true
      export_sc_on_disk: false
